### PR TITLE
ZIO 2 migration

### PR DESCRIPTION
**Pull request by atooni**
This is a PR migrating uzhttp to zio-2.0.0-RC1

### CODE REVIEW

**Comment by jeremyrsmith** [comment]
Thanks for keeping this going @atooni. Let's put the version of this to `0.3.0-RC1`, and we can merge and start publishing artifacts (now that ZIO is in RC stage)

**Comment by atooni** [comment]
@jeremyrsmith - that would be awesome - then I can fix my pre release of ZMX as well

**Comment by atooni** [comment]
> Thanks for keeping this going @atooni. Let's put the version of this to `0.3.0-RC1`, and we can merge and start publishing artifacts (now that ZIO is in RC stage)

bumped the uzhttp version in build.sbt

**Comment by jeremyrsmith** [comment]
@atooni thanks! If CI passes I'll go ahead and merge, and do an RC release.

Again, thanks for following this PR!

**Comment by atooni** [comment]
> @atooni thanks! If CI passes I'll go ahead and merge, and do an RC release.
> 
> Again, thanks for following this PR!

Hopefully goes thrugh now - my pleasure - thanks for open sourcing that kind of thing

**Comment by jeremyrsmith** [comment]
Apologies @atooni – I have been trying to publish it, but sonatype keeps giving me trouble. Not sure if it's a transient thing, or something I've done wrong, but in any case it's not for lack of trying.

**Comment by atooni** [comment]
> Apologies @atooni – I have been trying to publish it, but sonatype keeps giving me trouble. Not sure if it's a transient thing, or something I've done wrong, but in any case it's not for lack of trying.

We had problems publishing to Sonatype ourselves - thanks for letting me know. Lets hope it will get better :D

**Comment by jeremyrsmith** [comment]
It looks like my last attempt worked: https://mvnrepository.com/artifact/org.polynote/uzhttp_3/0.3.0-RC1

So I will tag a release and then close the relevant tickets.

**Pull request merged**
